### PR TITLE
Player Bio #8 Retrieve bio information after calling get_player_stats()

### PR DESCRIPTION
**Pull request by adrperez5**
In the method get_player_stats(), the new private function named _get_bio_info() will read in the bio information of the player object. The information is stored in the new player attribute "metadata" in the form of a Python dictionary.

Added a test case in players/tests/test_models.py. 

Added documentation for the new attribute.

### CODE REVIEW

**Review by RamParameswaran — COMMENTED** [review]
Hi. Looks good to me. The test you added sufficiently covers the happy path. 
One small nice-to-have would be if you added a test which covers the unhappy path (where the players bio doesn't exist in the HTML. I don't know if this unhappy path ever occurs. But nonetheless I think the `if` block would catch this case... 

Anyways, looks good!
One thing you will need to do is bump the version in the `setup.py` file. Version "0.4.3" is fine. Then I can merge it and release it to PyPi so anyone else who installs the package via Pip will get your contributions too. Once you've done that I'll approve and merge the PR.

**Comment by adrperez5** [comment]
I have a few questions about the requirements for the unhappy path, should
I replace the non-existent bio string with “”, none, or something like “Not
Available”?

**Comment by RamParameswaran** [comment]
I think return None. That way the 3 keys are always present in the
dictionary, so users can always expect them to be present. But if the data
is unavailable the values will be None. What do you think?

**Comment by adrperez5** [comment]
I think that sounds good. I added error handling for unavailable player bio information. Such that if any of the information is missing, it will assign None to the corresponding value in player.metadata. In addition, if "born" does not exist/None, neither will "debut" or "last" (it would be unable to calculate the date for "debut" and "last" without the "born" info). 

I also added a test to assure non-existent information is being handled correctly.

**Review by RamParameswaran — APPROVED** [review]
Looks great. Approved and merged. Thanks! 🚀

**Comment by RamParameswaran** [comment]
And I've published the latest version to PyPi v0.4.3 🙂 nice first contribution!

**Comment by adrperez5** [comment]
Thank you, I really appreciate it!

**Pull request merged**
